# Generated by Django 5.0.8 on 2024-08-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
